services:
  app:
    build:
      context: .
      target: dev
    env_file: .env
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - .:/app
    networks:
      - monitoring-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  loki:
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
    networks:
      - monitoring-net

  promtail:
    image: grafana/promtail:3.5.0
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:12.0.0
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    depends_on:
      - loki
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge

volumes:
  loki-data:
  promtail-data:
  grafana-data:
